accounts/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.views import login, logout
from accounts.views import register, profile, profile_edit, account_edit, overview, RegisterWizard, activate
from django.contrib.auth.views import password_change, password_change_done, password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from accounts.forms import UserAccountForm, UserCreationFormExtended, UserProfileForm, UserProfileForm1, UserProfileForm2 
from django.views.generic.simple import direct_to_template
from django.contrib.auth.views import login,logout
urlpatterns = patterns('',
    url(r'^login/$',  login, name="login"),
    url(r'^logout/$', logout, name="logout"),
    url(r'^register/$', RegisterWizard([UserCreationFormExtended, UserProfileForm1, UserProfileForm2]), name="register"),
    url(r'^register/success/$', direct_to_template, {'template': 'success.html' }, name="success"), 
    url(r'^overview/$', overview, name="overview"), 
    url(r'^profile/$', profile, name="profile"), 
    url(r'^profile/edit/$', profile_edit, name="profile-edit"),
    url(r'^edit/$', account_edit, name="account-edit"),
    url(r'^password-change/$', password_change),
    url(r'^password-change/done/$', password_change_done),
    url(r'^password-reset/$', password_reset),
    url(r'^password-reset/complete/$', password_reset_complete),
    url(r'^password-reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm),
    url(r'^password-reset/done/$', password_reset_done),
    url(r'^activate/(?P<verification_key>\w+)/$', activate, name="activate"),
    url(r'^(?P<username>[-\w]+)/$', profile, name="profile"),
    url(r'^$', overview, name="overview"),
)

ratings/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^submit', 'ratings.views.record_vote'),
    (r'^test', 'ratings.views.testview')
    )

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from pages.views import page_handler

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^account/', include('accounts.urls')),
	(r'^projects/', include('projects.urls')),
	(r'^contact/', include('contact.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^ratings/', include('ratings.urls')),
	url(r'(.*)/$|^$', page_handler, name="page"),
)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import PhoneNumberField 
from tagging.fields import TagField
from django.template.defaultfilters import slugify

class Project(models.Model):
    name = models.CharField('Project Name', max_length = 100, unique=True)
    slug = models.SlugField(unique=True)
    company = models.CharField('Corporation', max_length = 100, blank = True)
    date_created = models.DateTimeField(auto_now_add=True)
    founded = models.DateTimeField(auto_now_add=True,blank=True)
    phone = PhoneNumberField(blank=True,)
    email = models.EmailField(max_length=75)
    url = models.URLField(verify_exists=True)
    youtube_intro = models.URLField('Youtube Intro',verify_exists=True, blank=True)
    description = models.TextField('Pitch')
    markets = models.TextField()
    customers = models.TextField('Customers')
    revenue_model = models.TextField('Revenue Model')
    strategy = models.TextField('Sales Strategy')
    tax_id = models.CharField('Tax ID #',max_length=20, blank = True)
    funding_target = models.DecimalField('Current Funding',max_digits = 10, decimal_places=2)
    funding_current = models.DecimalField('Needed Funding',max_digits = 10, decimal_places=2)
    dab_score = models.DecimalField('D&B Score',max_digits = 10,decimal_places=0, blank = True)
    street_line1 = models.CharField('Address 1', max_length = 100, blank = True)
    street_line2 = models.CharField('Address 2', max_length = 100, blank = True)
    city = models.CharField('City', max_length = 100, blank = True)
    state = models.CharField('State', max_length = 100, blank = True)
    zip = models.DecimalField('ZIP', max_digits = 5, decimal_places=0)
    country = models.CharField('Country', max_length = 100, blank = True)
    tags = TagField(blank=True)
    owner = models.ForeignKey(User)    
    is_public = models.BooleanField('List Publically',default=False)

    def save(self):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Project, self).save()         

    def check_member(self, user):
        """Checks the exist of user in a project, if so returns member."""
        members = self.projectmember_set.all()
        if user in [member.user for member in members]:
            return members.get(user=user)

    def __unicode__(self):
        return 'Project - %s' % (self.name,)

class ProjectMember(models.Model):
    LEVELS = (
        ('1', 'Stage 1'),
        ('2', 'Stage 2'),
        ('3', 'Stage 3'),
        ('4', 'Stage 4'),
    )
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    level = models.IntegerField(choices=LEVELS, default=1)
    def __unicode__(self):
        return self.user.username

class ProjectFavorite(models.Model):
    project = models.ForeignKey(Project)
    user = models.ForeignKey(User)

    class Meta:
        unique_together = (('project', 'user' )) #this makes it unique at the db level

    def __unicode__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.db import models
from django.contrib.localflavor.us.models import PhoneNumberField 
from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm

class UserAccountForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('user_permissions', 'groups', 'is_active', 'is_staff', 'is_superuser', 'password','last_login','date_joined')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('user',)

class UserCreationFormExtended(UserCreationForm): 
    class Meta: 
        model = User 
        fields = ('username', 'email', 'first_name', 'last_name')

class UserProfileForm1(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('company','title','url','background','performance')

class UserProfileForm2(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone_home','phone_office','phone_mobile','street_line1','street_line2','city','state','zip','country')

accounts/views.py
from django.contrib import auth
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, get_object_or_404
from accounts.forms import UserProfileForm, UserAccountForm, UserCreationFormExtended, UserProfileForm1, UserProfileForm2
from django.template import RequestContext
from django.contrib.auth.models import User
from accounts.models import UserProfile
from django.core.urlresolvers import reverse
from projects.models import Project
from django.contrib.auth.decorators import login_required
from django.contrib.formtools.wizard import FormWizard
from django.core.mail import send_mail
from django.conf import settings

@login_required
def overview(request):
    user = request.user
    profile = user.get_profile()
    projects = Project.objects.filter(owner=user)
    return render_to_response("overview.html", {
        'user': user,
        'profile': profile,
        'projects': projects,
    }, context_instance=RequestContext(request))

@login_required 
def account_edit(request):
    account = request.user
    if request.method == 'POST':
        form = UserAccountForm(request.POST, instance=account)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('overview'))
    else:
        form = UserAccountForm(instance=account)
    return render_to_response("account.html", {
        'account_form': form,
    }, context_instance=RequestContext(request))

def profile(request, username=None):
    if username: 
        user = User.objects.get(username=username)
        profile = user.get_profile()
    else:
        user = request.user
        profile = user.get_profile()
    return render_to_response("profile.html", {
        'user': user,
        'profile': profile,
    }, context_instance=RequestContext(request))

@login_required 
def profile_edit(request):
    user = request.user
    profile = user.get_profile()
    if request.method == 'POST':
        form = UserProfileForm(request.POST,request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('profile', args=[user.username]))
    else:
        form = UserProfileForm(instance=profile)
    return render_to_response("edit.html", {
        'profile_form': form,
    }, context_instance=RequestContext(request))

def register(request):         
    if request.method == 'POST':
        form = UserCreationFormExtended(request.POST,request.FILES)
        if form.is_valid():   
            new_user = form.save()
            new_profile = UserProfile(user=new_user) #create new profile with new_user instance
            new_profile.save()            
            return HttpResponseRedirect(reverse('success'))
    else:                     
        form = UserCreationFormExtended()
    return render_to_response("register.html", locals(), context_instance=RequestContext(request))

class RegisterWizard(FormWizard):
    def done(self, request, form_list):
        for form in form_list:
            if isinstance(form, UserCreationFormExtended):
                user = form.save()
                #set to not active
                user.is_active = 0
                user.save()
            if isinstance(form, UserProfileForm1):
                profile = form.save(commit=False)
                profile.user = user
            if isinstance(form, UserProfileForm2):
                tempprofile = form.save(commit=False)
                for f in form.fields.keys():
                    setattr(profile, f, getattr(tempprofile, f))
                profile.save()
            
        user = User.objects.get(username=user.username)
        message = """Testing for now here's your verifaction URL: http://visodea.com/account/activate/%s """ % (user.get_profile().verification_key) 
        send_mail('Please verify your email', message, 'support@visodea.com', [user.email], fail_silently=False) 
        return HttpResponseRedirect(reverse('success'))
    
    def get_template(self, step):
        return 'register_%s.html' % step

def activate(request, verification_key):
    url_key = verification_key
    profile = get_object_or_404(UserProfile, verification_key=url_key) #404's if key is not found 
    user = profile.user
    user.is_active = 1 #set user to active so they may login
    user.save()
    return render_to_response('email_verified.html', (), context_instance=RequestContext(request))

accounts/templates/account.html
{% extends "base.html" %}

{% block title %}Edit Account{% endblock %}

{% block content %}
<div class="pageContent">
  <form action="" method="post"> {% csrf_token %}
  <h4>Edit Account</h4>
      {{ account_form.as_p }}
      <input type="submit" value="Save Changes" class="submitBtn">
  </form>
</div>
{% endblock %}

accounts/templates/account_detail.html
{% extends 'base.html' %}

{% block content %}
<h3> Account Detail </h3>

{% endblock %}

accounts/templates/edit.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<div class="section">
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
  <h4>Edit Profile</h4>
      {{ profile_form.as_p }}
      <input type="submit" value="Save My Profile" class="submitBtn">
  </form>
  </div>
{% endblock %}

accounts/templates/email_verified.html
{% extends "base.html" %}

{% block title %}Email Verification Success{% endblock %}

{% block content %}
<h3>Great Success!</h3>
<p> You've successfully verfied your email address. You are now able to <a href="{% url login %}">Login</a>
{% endblock %}

accounts/templates/overview.html
{% extends 'base.html' %}
{% block title %}My Projects{% endblock %}
{% block path %}id="overview"{% endblock %}

{% block sidebar %}
<ul class="side-nav">
	<li><a href="/account" class="submitBtn">Notifications</a></li> 
	<li><a href="/projects/add" class="submitBtn">Add a new project</a></li>
</ul>
{% endblock %}

{% block content %}
<div class="pageContent">
	<div class="section">
		<h4>Your projects</h4>
	</div>
{% for project in projects %}
	<div class="result">
	<h4><a href="{% url project-detail slug=project.slug %}">{{ project.name }}</a></h4>
	<p>Created: <span class="bold">{{ project.date_created|date:"F j Y"}}</span></p>
		<div class="options">
			<a class="favorite" href="/projects/{{ project.name }}/edit">edit</a>
			<ul class="dropdown">
				<li>share
				<ul class="shareLinks" id="{{ project.name }}">
					<li><a href="mailto:?subject={{ project.name }} - Visodea.com&body=http://visodea.com/project/{{ project.slug }}" class="shareEmail">Email</a></li>
					<li id="twitter"><a title="http://www.twitter.com" class="shareTwitter">Twitter</a></li>
					<li id="facebook"><a title="http://www.facebook.com" class="shareFacebook">Facebook</a></li>
				</ul>
				</li>
			</ul>
			<a href="/projects/{{ project.slug }}" class="viewProject">view project ></a>
		</div>
	</div>
{% endfor %}
</div>
{% endblock %}

accounts/templates/profile.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}Viewing Profile for {{ user.username }}{% endblock %}
{% block path %}id="profile"{% endblock %}

{% block content %}

<div class="profilesec">
<div id="profilepic">
{% if profile.photo %} <img src="{{ profile.photo|thumbnail:"125x125" }}">{% endif %}
<h4>{{ user.username}}</h4>
</div>

<div class="profileinfo">
<p><span class="highlight">Name:</span>  {{ user.first_name }} {{ user.last_name }}</p>
{% if profile.company %}<p><span class="highlight">Company:</span>  {{ profile.company }}</p>{% endif %}
{% if profile.url %}<p><span class="highlight">Website:</span>   <a href="{{ profile.url }}" target="_blank">{{ profile.url }}</a></p>{% endif %}
{% if profile.title %}<p><span class="highlight">Profession/Title: </span>{{ profile.title }}</p> {% endif %}
{% if profile.city %}<p><span class="highlight">City:</span>  {{ profile.city }}</p>{% endif %}
{% if profile.state %}<p><span class="highlight">State:</span>  {{ profile.state }}</p>{% endif %}
{% if profile.country %}<p><span class="highlight">Country:</span>  {{ profile.country }}</p>{% endif %}
<div class="profilebg">{% if profile.background %}<p><span class="highlight">Background:</span>  {{ profile.background }}</p>{% endif %}</div>
<div class="profilebg">{% if profile.city %}<p><span class="highlight">Performance:</span>  {{ profile.performance }}</p>{% endif %}</div>

<div class="projectfav"></div>
{% if user.projectfavorite_set.all %}
<h2>{{ user.first_name }}'s Favorite Projects</h2>

{% for fav in user.projectfavorite_set.all %}
<p><a href="{% url project-detail fav.project.slug %}">{{ fav.project.name}}</a></p> 
{% endfor %}

{% endif %}
</div>
</div>

</div>

{% endblock %}

accounts/templates/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}

<h3>Create an account</h3>


  <form action="" method="post"> {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create my account!" class="submitBtn">
  </form>
{% endblock %}

accounts/templates/register_0.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block sidebar %}
<ul class="side-nav">
	<li class="first"><a href="/">home</a></li>
	<li><a href="/about-us">about visodea</a></li>
	<li class="last"><a href="/getting-started">getting started</a></li>
</ul><!-- end nav -->
{% endblock %}
{% block content %}
<div class="pageContent">
<div class="steps">
	<ul>
		<li class="current">The Basics</li>
		<li>Professional Background</li>
		<li class="last">Contact Information</li>
	</ul>
</div> 
<p class="skipStep">Step {{ step }} of {{ step_count }}</p>

<form action="" method="post"> {% csrf_token %}
<h4>Lets start with the basics.</h4>
  {{ form.as_p }}

  <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
  {{ previous_fields|safe }}
  <input type="submit" value="Next" class="submitBtn">  
</form>
</div>


 
{% endblock %}

accounts/templates/register_1.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block sidebar %}
<ul class="side-nav">
	<li class="first"><a href="/">home</a></li>
	<li><a href="/about-us">about visodea</a></li>
	<li class="last"><a href="/getting-started">getting started</a></li>
</ul><!-- end nav -->
{% endblock %}
{% block content %}
<div class="pageContent">



<div class="steps">
	<ul>
		<li>The Basics</li>
		<li class="current">Professional Background</li>
		<li class="last">Contact Information</li>
	</ul>
</div> 
 
<p class="skipStep">Step {{ step }} of {{ step_count }}</p>

<form action="" method="post"> {% csrf_token %}
<h4>Share some details about your professional background</h4>
  {{ form.as_p }}

  <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
  {{ previous_fields|safe }}
  <input type="submit" value="Next" class="submitBtn"> 
</form>
  
</div>
{% endblock %}

accounts/templates/register_2.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block sidebar %}
<ul class="side-nav">
	<li class="first"><a href="/">home</a></li>
	<li><a href="/about-us">about visodea</a></li>
	<li class="last"><a href="/getting-started">getting started</a></li>
</ul><!-- end nav -->
{% endblock %}
{% block content %}
<div class="pageContent">
<div class="steps">
	<ul>
		<li>The Basics</li>
		<li>Professional Background</li>
		<li class="current last">Contact Information</li>
	</ul>
</div> 
 
<p class="skipStep">Step {{ step }} of {{ step_count }}</p>

<form action="" method="post"> {% csrf_token %}
<h4>Contact information</h4>
  {{ form.as_p }}
  <input type="hidden" name="{{ step_field }}" value="{{ step0 }}" />
  {{ previous_fields|safe }}
  <input type="submit" value="Create Account" class="submitBtn"> 
</form>
</div>
{% endblock %}

accounts/templates/success.html
{% extends 'base.html' %}

{% block sidebar %}

{% endblock %}
{% block content %}
<div class="pageContent">
<h3> Registration Successful </h3>
<p> Welcome to visodea, you may now <a href="{% url login %}">log in</a>.
</div>
{% endblock %}